# Nixpacks configuration to point to the UI folder
[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd ui && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd ui && npm run build"]

[start]
cmd = "cd ui && npm run start"

[variables]
BACKEND_URL = "http://q8gwg4co8084cko8ss4kwo04.168.231.103.94.sslip.io"
